#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'build-essential'
cookbook 'git', git: 'https://github.com/fnichol/chef-git.git'
cookbook 'imagemagick'
cookbook 'curl'

cookbook 'nginx'
cookbook 'unicorn'

cookbook 'mysql'
cookbook 'mongodb'

cookbook 'memcached', :git => 'https://github.com/hectcastro/chef-memcached'
cookbook 'redis', :git => 'https://github.com/ctrabold/chef-redis'

cookbook 'vim'
cookbook 'rvm'
